// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/acl": {
            "get": {
                "description": "Returns a list of all ACLs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ACL Management"
                ],
                "summary": "Get all ACLs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.getACL"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/acl/{ip}": {
            "get": {
                "description": "Returns ACL details for a specific IP address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ACL Management"
                ],
                "summary": "Get ACL details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP Address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.getACL"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates ACL configuration for an IP address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ACL Management"
                ],
                "summary": "Update an existing ACL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP Address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "ACL configuration",
                        "name": "acl",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.modifyACL"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.getACL"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new ACL for an IP address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ACL Management"
                ],
                "summary": "Add a new ACL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP Address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "ACL configuration",
                        "name": "acl",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.addACL"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.getACL"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an ACL for a specific IP address",
                "tags": [
                    "ACL Management"
                ],
                "summary": "Delete an ACL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP Address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.getACL"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/authorize": {
            "get": {
                "description": "Configure NGINX auth_request to this endpoint",
                "tags": [
                    "Authorization"
                ],
                "summary": "NGINX auth_request destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP address of the user",
                        "name": "X-Real-IP",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the host (FQDN) the user is making a request to",
                        "name": "Host",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "access granted"
                    },
                    "401": {
                        "description": "unauthorized - user IP is unknown or not permitted to access this host"
                    }
                }
            }
        },
        "/challenge": {
            "post": {
                "description": "A user must successfully POST to this URL in order for their IP address to be granted access",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Challenge used to authorize an IP address for access",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP address of the user",
                        "name": "X-Real-IP",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID (4-64 characters)",
                        "name": "User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Secret that was given to/by the user",
                        "name": "User-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "challenge was accepted: the value of X-Real-IP has been granted an ACL"
                    },
                    "400": {
                        "description": "bad request: X-Real-IP is not set or User-ID is invalid"
                    },
                    "401": {
                        "description": "unauthorized: the user secret is incorrect or the user is disabled"
                    },
                    "500": {
                        "description": "server could not process the request"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "Returns a list of all users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Get all users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.getUser"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new user with the provided configuration. User ID must be provided (4-64 characters).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Add a new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User configuration",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.addUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.getUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Returns details for a specific user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Get user details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.getUser"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates user configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Update an existing user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User configuration",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.modifyUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.getUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a user from the system",
                "tags": [
                    "User Management"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Admin secret for authentication",
                        "name": "Admin-Secret",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.getUser"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.errorResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns version information about this server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Information"
                ],
                "summary": "Version information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.version"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.addACL": {
            "type": "object",
            "properties": {
                "allow_all": {
                    "description": "when true, client is allowed to access everything",
                    "type": "boolean",
                    "example": false
                },
                "allowed_hosts": {
                    "description": "represents a list of host headers the client is allowed to access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "git.example.com",
                        "wiki.example.com"
                    ]
                },
                "ttl": {
                    "description": "after this date, the ACL is no longer valid (RFC3339 format)",
                    "type": "string",
                    "example": "2025-12-31T23:59:59Z"
                },
                "user_ids": {
                    "description": "Users associated with this ACL",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "5e8848",
                        "a3f129"
                    ]
                }
            }
        },
        "server.addUser": {
            "type": "object",
            "properties": {
                "acl_allow_all": {
                    "description": "Determines if this User is allowed to access ALL resources",
                    "type": "boolean",
                    "example": false
                },
                "acl_allowed_hosts": {
                    "description": "A list of hosts (FQDN) this User is allowed to access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "git.example.com",
                        "wiki.example.com"
                    ]
                },
                "description": {
                    "description": "A brief description of this User",
                    "type": "string",
                    "example": "Cloud Strife"
                },
                "dns_names": {
                    "description": "A list of DNS names that resolve this User's IPs which get whitelisted automatically without a challenge.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "myhome.no-ip.info"
                    ]
                },
                "enabled": {
                    "description": "Determines if this User is enabled",
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "description": "A unique identifier for this User (4-64 characters)",
                    "type": "string",
                    "example": "cloud"
                },
                "secret": {
                    "description": "This secret is used as a challenge to whitelist a User's IP",
                    "type": "string",
                    "example": "supersecret"
                },
                "ttl_minutes": {
                    "description": "Represents the number of minutes this User's IP is whitelisted for after a successful challenge",
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "server.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "server.getACL": {
            "type": "object",
            "properties": {
                "allow_all": {
                    "description": "when true, client is allowed to access everything",
                    "type": "boolean",
                    "example": false
                },
                "allowed_hosts": {
                    "description": "represents a list of host headers the client is allowed to access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "git.example.com",
                        "wiki.example.com"
                    ]
                },
                "ip_address": {
                    "description": "IP address this ACL applies to",
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "ttl": {
                    "description": "after this date, the ACL is no longer valid (RFC3339 format)",
                    "type": "string",
                    "example": "2025-12-31T23:59:59Z"
                },
                "user_ids": {
                    "description": "Users associated with this ACL",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "5e8848",
                        "a3f129"
                    ]
                }
            }
        },
        "server.getUser": {
            "type": "object",
            "properties": {
                "acl_allow_all": {
                    "description": "Determines if this User is allowed to access ALL resources",
                    "type": "boolean",
                    "example": false
                },
                "acl_allowed_hosts": {
                    "description": "A list of hosts (FQDN) this User is allowed to access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "git.example.com",
                        "wiki.example.com"
                    ]
                },
                "description": {
                    "description": "A brief description of this User",
                    "type": "string",
                    "example": "Cloud Strife"
                },
                "dns_names": {
                    "description": "A list of DNS names that resolve this User's IPs which get whitelisted automatically without a challenge.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "myhome.no-ip.info"
                    ]
                },
                "enabled": {
                    "description": "Determines if this User is enabled",
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "description": "A unique identifier for this User (4-64 characters)",
                    "type": "string",
                    "example": "cloud"
                },
                "ttl_minutes": {
                    "description": "Represents the number of minutes this User's IP is whitelisted for after a successful challenge",
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "server.modifyACL": {
            "type": "object",
            "properties": {
                "allow_all": {
                    "description": "when true, client is allowed to access everything",
                    "type": "boolean",
                    "example": false
                },
                "allowed_hosts": {
                    "description": "represents a list of host headers the client is allowed to access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "git.example.com",
                        "wiki.example.com"
                    ]
                },
                "ttl": {
                    "description": "after this date, the ACL is no longer valid (RFC3339 format)",
                    "type": "string",
                    "example": "2025-12-31T23:59:59Z"
                },
                "user_ids": {
                    "description": "Users associated with this ACL",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "5e8848",
                        "a3f129"
                    ]
                }
            }
        },
        "server.modifyUser": {
            "type": "object",
            "properties": {
                "acl_allow_all": {
                    "description": "Determines if this User is allowed to access ALL resources",
                    "type": "boolean",
                    "example": false
                },
                "acl_allowed_hosts": {
                    "description": "A list of hosts (FQDN) this User is allowed to access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "git.example.com",
                        "wiki.example.com"
                    ]
                },
                "description": {
                    "description": "A brief description of this User",
                    "type": "string",
                    "example": "Cloud Strife"
                },
                "dns_names": {
                    "description": "A list of DNS names that resolve this User's IPs which get whitelisted automatically without a challenge.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "myhome.no-ip.info"
                    ]
                },
                "enabled": {
                    "description": "Determines if this User is enabled",
                    "type": "boolean",
                    "example": true
                },
                "ttl_minutes": {
                    "description": "Represents the number of minutes this User's IP is whitelisted for after a successful challenge",
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "server.version": {
            "type": "object",
            "properties": {
                "build_ref": {
                    "type": "string",
                    "example": "git-30b8019"
                },
                "version": {
                    "type": "string",
                    "example": "v1.0"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
